"""Сборка автономного CORAX Agent .exe (PyInstaller onefile, Win10/11)."""

from __future__ import annotations

import importlib.util
import json
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

from sqlalchemy.ext.asyncio import AsyncSession

from app.agent_bundle import _resolve_agent_token
from app.schemas import AgentBundleCreate, AgentExeCreate

_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
_AGENT_PYTHON = _PROJECT_ROOT / "agent" / "python"
_EXE_NAME = "CORAX-Agent"


def exe_build_available() -> tuple[bool, str | None]:
    if sys.platform != "win32":
        return False, "Сборка EXE доступна только на Windows-сервере CORAX."
    if not _AGENT_PYTHON.is_dir():
        return False, f"Не найдена папка агента: {_AGENT_PYTHON}"
    if importlib.util.find_spec("PyInstaller") is None:
        return False, "Установите PyInstaller на сервере: pip install pyinstaller"
    for name in ("agent.py", "corax_gui.py"):
        if not (_AGENT_PYTHON / name).is_file():
            return False, f"Не найден файл agent/python/{name}"
    return True, None


def _write_embedded(work: Path, server: str, token: str) -> None:
    content = (
        "# Auto-generated by CORAX admin — do not commit.\n"
        f"SERVER = {json.dumps(server)}\n"
        f"TOKEN = {json.dumps(token)}\n"
    )
    (work / "corax_embedded.py").write_text(content, encoding="utf-8")


def _write_entry(work: Path) -> None:
    (work / "corax_run.py").write_text(
        "from corax_gui import main\n\n"
        'if __name__ == "__main__":\n'
        "    raise SystemExit(main())\n",
        encoding="utf-8",
    )


def _ensure_agent_deps() -> None:
    req = _AGENT_PYTHON / "requirements.txt"
    if not req.is_file():
        return
    subprocess.run(
        [sys.executable, "-m", "pip", "install", "-q", "-r", str(req)],
        check=True,
        capture_output=True,
        text=True,
        timeout=180,
    )


def build_agent_exe(server: str, token: str) -> tuple[bytes, str]:
    ok, reason = exe_build_available()
    if not ok:
        raise RuntimeError(reason or "EXE build unavailable")

    stamp = datetime.now(timezone.utc).strftime("%Y%m%d")
    filename = f"corax-agent-win10-{stamp}.exe"

    with tempfile.TemporaryDirectory(prefix="corax-exe-") as tmp:
        work = Path(tmp)
        shutil.copy2(_AGENT_PYTHON / "agent.py", work / "agent.py")
        shutil.copy2(_AGENT_PYTHON / "corax_gui.py", work / "corax_gui.py")
        _write_embedded(work, server, token)
        _write_entry(work)

        _ensure_agent_deps()

        cmd = [
            sys.executable,
            "-m",
            "PyInstaller",
            "--onefile",
            "--windowed",
            "--name",
            _EXE_NAME,
            "--clean",
            "--noconfirm",
            "--log-level=WARN",
            "--hidden-import=psutil",
            "--hidden-import=requests",
            "--collect-submodules=psutil",
            str(work / "corax_run.py"),
        ]
        try:
            proc = subprocess.run(
                cmd,
                cwd=work,
                capture_output=True,
                text=True,
                timeout=600,
                check=False,
            )
        except subprocess.TimeoutExpired as exc:
            raise RuntimeError("Сборка EXE превысила лимит 10 минут") from exc

        if proc.returncode != 0:
            tail = (proc.stderr or proc.stdout or "")[-2000:]
            raise RuntimeError(f"PyInstaller завершился с ошибкой:\n{tail}")

        exe_path = work / "dist" / f"{_EXE_NAME}.exe"
        if not exe_path.is_file():
            raise RuntimeError("PyInstaller не создал CORAX-Agent.exe")

        return exe_path.read_bytes(), filename


async def build_agent_exe_for_request(db: AsyncSession, body: AgentExeCreate) -> tuple[bytes, str]:
    server = body.server_url.strip().rstrip("/")
    if not server.lower().startswith(("http://", "https://")):
        raise ValueError("server_url должен начинаться с http:// или https://")

    token, _ = await _resolve_agent_token(
        db,
        AgentBundleCreate(
            server_url=body.server_url,
            create_token=body.create_token,
            token_label=body.token_label,
            allowed_hostname=body.allowed_hostname,
            existing_token=body.existing_token,
        ),
    )
    return build_agent_exe(server, token)
