#!/usr/bin/env python3
"""Idempotent Docker bootstrap for backend/.env.

If backend/.env is missing, copy backend/.env.example and fill strong secrets.
If the file already exists, do nothing (safe to call on every docker:up).

Usage:
  python scripts/ensure_docker_env.py
"""

from __future__ import annotations

import secrets
import string
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BACKEND = ROOT / "backend"
ENV_PATH = BACKEND / ".env"
EXAMPLE_PATH = BACKEND / ".env.example"
CREDENTIALS_PATH = BACKEND / ".docker-credentials"

# Keys that must be strong for Docker production (compose + _validate_production_settings).
SECRET_KEYS = (
    "SECRET_KEY",
    "AGENT_TOKEN",
    "AGENT_TOKEN_PEPPER",
    "POSTGRES_PASSWORD",
    "BOOTSTRAP_ADMIN_PASSWORD",
)


def _hex_secret(nbytes: int = 32) -> str:
    return secrets.token_hex(nbytes)


def _admin_password(length: int = 20) -> str:
    alphabet = string.ascii_letters + string.digits
    # Avoid ambiguous characters in printed credentials.
    alphabet = alphabet.replace("O", "").replace("0", "").replace("l", "").replace("I", "")
    return "".join(secrets.choice(alphabet) for _ in range(length))


def _set_env_value(text: str, key: str, value: str) -> str:
    """Replace KEY=... line or append if missing. Preserves comments / order."""
    prefix = f"{key}="
    lines = text.splitlines(keepends=True)
    out: list[str] = []
    found = False
    for line in lines:
        raw = line.lstrip()
        if raw.startswith("#") or "=" not in line:
            out.append(line)
            continue
        k = line.split("=", 1)[0].strip()
        if k == key:
            nl = "\n" if line.endswith("\n") else ""
            out.append(f"{prefix}{value}{nl}")
            found = True
        else:
            out.append(line)
    if not found:
        if out and not out[-1].endswith("\n"):
            out[-1] = out[-1] + "\n"
        out.append(f"{prefix}{value}\n")
    return "".join(out)


def _get_env_value(text: str, key: str) -> str | None:
    for line in text.splitlines():
        raw = line.strip()
        if not raw or raw.startswith("#") or "=" not in raw:
            continue
        k, _, v = raw.partition("=")
        if k.strip() == key:
            return v.strip()
    return None


def _write_credentials(username: str, password: str, port: str) -> None:
    body = (
        "# Generated by scripts/ensure_docker_env.py — do not commit.\n"
        f"URL=http://127.0.0.1:{port}/\n"
        f"BOOTSTRAP_ADMIN_USERNAME={username}\n"
        f"BOOTSTRAP_ADMIN_PASSWORD={password}\n"
        f"ENV_FILE={ENV_PATH.as_posix()}\n"
    )
    CREDENTIALS_PATH.write_text(body, encoding="utf-8")


def _print_credentials(username: str, password: str, port: str) -> None:
    print("")
    print("=== CORAX Docker - first-run credentials ===")
    print(f"  Panel:    http://127.0.0.1:{port}/")
    print(f"  Username: {username}")
    print(f"  Password: {password}")
    print(f"  Saved:    {CREDENTIALS_PATH.relative_to(ROOT).as_posix()}")
    print(f"  Env:      {ENV_PATH.relative_to(ROOT).as_posix()}")
    print("  Change the admin password in the panel after first login.")
    print("===========================================")
    print("")


def main() -> int:
    if not EXAMPLE_PATH.is_file():
        print(f"ERROR: missing template {EXAMPLE_PATH}", file=sys.stderr)
        return 1

    if ENV_PATH.is_file():
        text = ENV_PATH.read_text(encoding="utf-8")
        username = _get_env_value(text, "BOOTSTRAP_ADMIN_USERNAME") or "admin"
        port = _get_env_value(text, "CORAX_PUBLISH_PORT") or "3000"
        # Do not re-print password from existing .env (may already be changed).
        print(f"[docker-env] Using existing {ENV_PATH.relative_to(ROOT).as_posix()} (not modified).")
        print(f"[docker-env] Panel: http://127.0.0.1:{port}/  (user: {username})")
        return 0

    text = EXAMPLE_PATH.read_text(encoding="utf-8")
    values: dict[str, str] = {
        "SECRET_KEY": _hex_secret(32),
        "AGENT_TOKEN": _hex_secret(32),
        "AGENT_TOKEN_PEPPER": _hex_secret(32),
        "POSTGRES_PASSWORD": _hex_secret(32),
        "BOOTSTRAP_ADMIN_PASSWORD": _admin_password(20),
        "BOOTSTRAP_ADMIN_USERNAME": "admin",
    }
    for key in SECRET_KEYS:
        text = _set_env_value(text, key, values[key])
    text = _set_env_value(text, "BOOTSTRAP_ADMIN_USERNAME", values["BOOTSTRAP_ADMIN_USERNAME"])

    banner = (
        "# Auto-generated by scripts/ensure_docker_env.py for Docker.\n"
        "# Re-run is a no-op while this file exists. Do not commit.\n"
        "#\n"
    )
    if not text.lstrip().startswith("# Auto-generated"):
        text = banner + text

    ENV_PATH.write_text(text, encoding="utf-8")
    port = _get_env_value(text, "CORAX_PUBLISH_PORT") or "3000"
    username = values["BOOTSTRAP_ADMIN_USERNAME"]
    password = values["BOOTSTRAP_ADMIN_PASSWORD"]
    _write_credentials(username, password, port)
    _print_credentials(username, password, port)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
