#!/usr/bin/env python3
"""Docker bootstrap for backend/.env.

- Missing .env  → create from .env.example with strong secrets.
- Existing .env → heal weak/placeholder secrets so production Docker can start.
  Strong values are left untouched (safe to call on every docker:up).

Usage:
  python3 scripts/ensure_docker_env.py
  npm run docker:init
"""

from __future__ import annotations

import secrets
import string
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BACKEND = ROOT / "backend"
ENV_PATH = BACKEND / ".env"
EXAMPLE_PATH = BACKEND / ".env.example"
CREDENTIALS_PATH = BACKEND / ".docker-credentials"

# Must satisfy backend/app/config.py _validate_production_settings + compose.
SECRET_KEYS = (
    "SECRET_KEY",
    "AGENT_TOKEN",
    "AGENT_TOKEN_PEPPER",
    "POSTGRES_PASSWORD",
    "BOOTSTRAP_ADMIN_PASSWORD",
)

# Explicit placeholders from .env.example / common lab typos (even if long enough).
_PLACEHOLDERS = {
    "change-me-in-production-use-openssl-rand-hex-32",
    "dev-agent-token-change-in-production",
    "dev-secret-key-change-me",
    "long-random-string-for-agents-min-24-chars",
    "generate-with-openssl-rand-hex-32",
    "change-me-strong-password-min-12",
    "admin123",
    "admin12345",
    "inventory",
    "postgres",
    "changeme",
    "password",
    "secret",
    "corax_password",
    "secret_key_change_me_123",
}


def _hex_secret(nbytes: int = 32) -> str:
    return secrets.token_hex(nbytes)


def _admin_password(length: int = 20) -> str:
    alphabet = string.ascii_letters + string.digits
    alphabet = alphabet.replace("O", "").replace("0", "").replace("l", "").replace("I", "")
    return "".join(secrets.choice(alphabet) for _ in range(length))


def _is_weak(key: str, value: str | None) -> bool:
    """Mirror production checks in backend/app/config.py (+ known placeholders)."""
    s = (value or "").strip()
    if not s:
        return True
    low = s.lower()
    if s in _PLACEHOLDERS or low in _PLACEHOLDERS:
        return True
    if low.startswith("replace-with-") or low.startswith("generate-with-"):
        return True
    if low.startswith("change-me") or low.startswith("your-"):
        return True
    if "change_me" in low or "change-me" in low:
        return True
    if key == "SECRET_KEY" and len(s) < 32:
        return True
    if key == "AGENT_TOKEN" and len(s) < 24:
        return True
    if key == "AGENT_TOKEN_PEPPER" and (not s or len(s) < 16):
        return True
    if key == "BOOTSTRAP_ADMIN_PASSWORD" and len(s) < 12:
        return True
    if key == "POSTGRES_PASSWORD" and len(s) < 12:
        return True
    return False


def _new_value(key: str) -> str:
    if key == "BOOTSTRAP_ADMIN_PASSWORD":
        return _admin_password(20)
    return _hex_secret(32)


def _set_env_value(text: str, key: str, value: str) -> str:
    prefix = f"{key}="
    lines = text.splitlines(keepends=True)
    out: list[str] = []
    found = False
    for line in lines:
        raw = line.lstrip()
        if raw.startswith("#") or "=" not in line:
            out.append(line)
            continue
        k = line.split("=", 1)[0].strip()
        if k == key:
            nl = "\n" if line.endswith("\n") else ""
            out.append(f"{prefix}{value}{nl}")
            found = True
        else:
            out.append(line)
    if not found:
        if out and not out[-1].endswith("\n"):
            out[-1] = out[-1] + "\n"
        out.append(f"{prefix}{value}\n")
    return "".join(out)


def _get_env_value(text: str, key: str) -> str | None:
    for line in text.splitlines():
        raw = line.strip()
        if not raw or raw.startswith("#") or "=" not in raw:
            continue
        k, _, v = raw.partition("=")
        if k.strip() == key:
            return v.strip()
    return None


def _write_credentials(username: str, password: str, port: str) -> None:
    body = (
        "# Generated by scripts/ensure_docker_env.py - do not commit.\n"
        f"URL=http://127.0.0.1:{port}/\n"
        f"BOOTSTRAP_ADMIN_USERNAME={username}\n"
        f"BOOTSTRAP_ADMIN_PASSWORD={password}\n"
        f"ENV_FILE={ENV_PATH.as_posix()}\n"
    )
    CREDENTIALS_PATH.write_text(body, encoding="utf-8")


def _print_credentials(username: str, password: str, port: str, *, healed: bool) -> None:
    title = "healed credentials" if healed else "first-run credentials"
    print("")
    print(f"=== CORAX Docker - {title} ===")
    print(f"  Panel:    http://127.0.0.1:{port}/")
    print(f"  Username: {username}")
    print(f"  Password: {password}")
    print(f"  Saved:    {CREDENTIALS_PATH.relative_to(ROOT).as_posix()}")
    print(f"  Env:      {ENV_PATH.relative_to(ROOT).as_posix()}")
    print("  Change the admin password in the panel after first login.")
    print("===========================================")
    print("")


def _ensure_username(text: str) -> tuple[str, str]:
    username = _get_env_value(text, "BOOTSTRAP_ADMIN_USERNAME") or "admin"
    if not username.strip():
        username = "admin"
        text = _set_env_value(text, "BOOTSTRAP_ADMIN_USERNAME", username)
    return text, username


def _apply_secrets(text: str, force_all: bool) -> tuple[str, list[str], dict[str, str]]:
    """Return updated text, list of healed keys, and final secret values."""
    healed: list[str] = []
    values: dict[str, str] = {}
    for key in SECRET_KEYS:
        current = _get_env_value(text, key)
        if force_all or _is_weak(key, current):
            values[key] = _new_value(key)
            text = _set_env_value(text, key, values[key])
            healed.append(key)
        else:
            values[key] = (current or "").strip()
    return text, healed, values


def main() -> int:
    if not EXAMPLE_PATH.is_file():
        print(f"ERROR: missing template {EXAMPLE_PATH}", file=sys.stderr)
        return 1

    created = not ENV_PATH.is_file()
    if created:
        text = EXAMPLE_PATH.read_text(encoding="utf-8")
        banner = (
            "# Auto-generated/healed by scripts/ensure_docker_env.py for Docker.\n"
            "# Weak secrets are replaced on docker:up. Do not commit.\n"
            "#\n"
        )
        text = banner + text
        text, healed, values = _apply_secrets(text, force_all=True)
    else:
        text = ENV_PATH.read_text(encoding="utf-8")
        text, healed, values = _apply_secrets(text, force_all=False)

    text, username = _ensure_username(text)
    port = _get_env_value(text, "CORAX_PUBLISH_PORT") or "3000"
    password = values["BOOTSTRAP_ADMIN_PASSWORD"]

    if created or healed:
        ENV_PATH.write_text(text, encoding="utf-8")
        if healed:
            print(f"[docker-env] Healed weak secrets in {ENV_PATH.relative_to(ROOT).as_posix()}:")
            for key in healed:
                print(f"  - {key}")
            if "POSTGRES_PASSWORD" in healed and not created:
                print(
                    "[docker-env] WARNING: POSTGRES_PASSWORD changed. "
                    "If DB volume already exists with another password, run:\n"
                    "  docker compose --env-file backend/.env down -v\n"
                    "  (this wipes DB data) then docker:up again."
                )
        _write_credentials(username, password, port)
        _print_credentials(username, password, port, healed=bool(healed) and not created)
        return 0

    print(f"[docker-env] Using existing {ENV_PATH.relative_to(ROOT).as_posix()} (secrets OK).")
    print(f"[docker-env] Panel: http://127.0.0.1:{port}/  (user: {username})")
    if not CREDENTIALS_PATH.is_file():
        _write_credentials(username, password, port)
        print(f"[docker-env] Wrote {CREDENTIALS_PATH.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
