#!/usr/bin/env python3
"""Docker bootstrap for backend/.env.

Lab-first defaults (LAN / VM):
- Missing .env  → create from .env.example with:
    BOOTSTRAP_ADMIN_PASSWORD=admin123
    POSTGRES_PASSWORD=inventory
    + strong SECRET_KEY / AGENT_TOKEN / AGENT_TOKEN_PEPPER
- Existing .env → NEVER rotate POSTGRES_* or non-empty BOOTSTRAP_*.
  Only fill/replace empty or placeholder JWT/agent keys (required to boot).
  Never print secret values to stdout (except intentional lab admin123 on first create).

Why we do not heal admin/postgres on existing files:
  Rotating BOOTSTRAP_ADMIN_PASSWORD does not update the DB password hash.
  Rotating POSTGRES_PASSWORD against an existing volume bricks the stack.

Usage:
  python3 scripts/ensure_docker_env.py
  npm run docker:init
"""

from __future__ import annotations

import secrets
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BACKEND = ROOT / "backend"
ENV_PATH = BACKEND / ".env"
EXAMPLE_PATH = BACKEND / ".env.example"
CREDENTIALS_PATH = BACKEND / ".docker-credentials"

DEFAULT_ADMIN_PASSWORD = "admin123"
DEFAULT_POSTGRES_PASSWORD = "inventory"

STRONG_KEYS = (
    "SECRET_KEY",
    "AGENT_TOKEN",
    "AGENT_TOKEN_PEPPER",
)

_PLACEHOLDERS = {
    "change-me-in-production-use-openssl-rand-hex-32",
    "dev-agent-token-change-in-production",
    "dev-secret-key-change-me",
    "long-random-string-for-agents-min-24-chars",
    "generate-with-openssl-rand-hex-32",
    "change-me-strong-password-min-12",
    "changeme",
    "password",
    "secret",
    "corax_password",
    "secret_key_change_me_123",
}


def _hex_secret(nbytes: int = 32) -> str:
    return secrets.token_hex(nbytes)


def _set_env_value(text: str, key: str, value: str) -> str:
    prefix = f"{key}="
    lines = text.splitlines(keepends=True)
    out: list[str] = []
    found = False
    for line in lines:
        raw = line.lstrip()
        if raw.startswith("#") or "=" not in line:
            out.append(line)
            continue
        k = line.split("=", 1)[0].strip()
        if k == key:
            nl = "\n" if line.endswith("\n") else ""
            out.append(f"{prefix}{value}{nl}")
            found = True
        else:
            out.append(line)
    if not found:
        if out and not out[-1].endswith("\n"):
            out[-1] = out[-1] + "\n"
        out.append(f"{prefix}{value}\n")
    return "".join(out)


def _get_env_value(text: str, key: str) -> str | None:
    for line in text.splitlines():
        raw = line.strip()
        if not raw or raw.startswith("#") or "=" not in raw:
            continue
        k, _, v = raw.partition("=")
        if k.strip() == key:
            return v.strip()
    return None


def _is_weak_strong_key(key: str, value: str | None) -> bool:
    s = (value or "").strip()
    if not s:
        return True
    low = s.lower()
    if s in _PLACEHOLDERS or low in _PLACEHOLDERS:
        return True
    if low.startswith("replace-with-") or low.startswith("generate-with-"):
        return True
    if low.startswith("change-me") or low.startswith("your-"):
        return True
    if "change_me" in low or "change-me" in low:
        return True
    if key == "SECRET_KEY" and len(s) < 32:
        return True
    if key == "AGENT_TOKEN" and len(s) < 24:
        return True
    if key == "AGENT_TOKEN_PEPPER" and len(s) < 16:
        return True
    return False


def _write_credentials(username: str, password: str, port: str) -> None:
    body = (
        "# Generated by scripts/ensure_docker_env.py - do not commit.\n"
        f"URL=http://127.0.0.1:{port}/\n"
        f"BOOTSTRAP_ADMIN_USERNAME={username}\n"
        f"BOOTSTRAP_ADMIN_PASSWORD={password}\n"
        f"ENV_FILE={ENV_PATH.as_posix()}\n"
    )
    CREDENTIALS_PATH.write_text(body, encoding="utf-8")


def _print_first_run(username: str, port: str) -> None:
    print("")
    print("=== CORAX Docker - first-run credentials ===")
    print(f"  Panel:    http://127.0.0.1:{port}/")
    print(f"  Username: {username}")
    print(f"  Password: {DEFAULT_ADMIN_PASSWORD}")
    print(f"  Saved:    {CREDENTIALS_PATH.relative_to(ROOT).as_posix()}")
    print("  After login the panel requires a new password (admin123 cannot stay).")
    print("  POSTGRES / JWT values are not printed.")
    print("===========================================")
    print("")


def _ensure_username(text: str) -> tuple[str, str]:
    username = _get_env_value(text, "BOOTSTRAP_ADMIN_USERNAME") or "admin"
    if not username.strip():
        username = "admin"
        text = _set_env_value(text, "BOOTSTRAP_ADMIN_USERNAME", username)
    return text, username


def _apply_first_create(text: str) -> str:
    text = _set_env_value(text, "BOOTSTRAP_ADMIN_PASSWORD", DEFAULT_ADMIN_PASSWORD)
    text = _set_env_value(text, "POSTGRES_PASSWORD", DEFAULT_POSTGRES_PASSWORD)
    text = _set_env_value(text, "SECRET_KEY", _hex_secret(32))
    text = _set_env_value(text, "AGENT_TOKEN", _hex_secret(32))
    text = _set_env_value(text, "AGENT_TOKEN_PEPPER", _hex_secret(32))
    text = _set_env_value(
        text,
        "DATABASE_URL",
        f"postgresql+asyncpg://inventory:{DEFAULT_POSTGRES_PASSWORD}@localhost:5432/inventory",
    )
    text = _set_env_value(
        text,
        "DIAGRAMS_DATABASE_URL",
        f"postgresql+asyncpg://inventory:{DEFAULT_POSTGRES_PASSWORD}@localhost:5432/inventory",
    )
    text = _set_env_value(
        text,
        "WAREHOUSE_DATABASE_URL",
        f"postgresql+asyncpg://inventory:{DEFAULT_POSTGRES_PASSWORD}@localhost:5432/inventory",
    )
    return text


def _repair_existing(text: str) -> tuple[str, list[str]]:
    """Never touch POSTGRES_*. Repair only weak JWT/agent keys. Bootstrap only if empty."""
    changed: list[str] = []
    for key in STRONG_KEYS:
        current = _get_env_value(text, key)
        if _is_weak_strong_key(key, current):
            text = _set_env_value(text, key, _hex_secret(32))
            changed.append(key)
    boot = (_get_env_value(text, "BOOTSTRAP_ADMIN_PASSWORD") or "").strip()
    if not boot:
        text = _set_env_value(text, "BOOTSTRAP_ADMIN_PASSWORD", DEFAULT_ADMIN_PASSWORD)
        changed.append("BOOTSTRAP_ADMIN_PASSWORD(empty→lab default)")
    return text, changed


def main() -> int:
    if not EXAMPLE_PATH.is_file():
        print(f"ERROR: missing template {EXAMPLE_PATH}", file=sys.stderr)
        return 1

    created = not ENV_PATH.is_file()
    if created:
        text = EXAMPLE_PATH.read_text(encoding="utf-8")
        banner = (
            "# Auto-generated by scripts/ensure_docker_env.py for Docker.\n"
            "# First raise: admin=admin123, POSTGRES_PASSWORD=inventory.\n"
            "# Existing .env: POSTGRES_* never rotated; JWT keys repaired if empty/placeholder.\n"
            "# Change admin password in the panel after first login. Do not commit.\n"
            "#\n"
        )
        text = banner + _apply_first_create(text)
        text, username = _ensure_username(text)
        port = _get_env_value(text, "CORAX_PUBLISH_PORT") or "3000"
        ENV_PATH.write_text(text, encoding="utf-8")
        _write_credentials(username, DEFAULT_ADMIN_PASSWORD, port)
        print(f"[docker-env] Created {ENV_PATH.relative_to(ROOT).as_posix()} (lab defaults).")
        _print_first_run(username, port)
        return 0

    text = ENV_PATH.read_text(encoding="utf-8")
    text, changed = _repair_existing(text)
    text, username = _ensure_username(text)
    port = _get_env_value(text, "CORAX_PUBLISH_PORT") or "3000"

    if changed:
        ENV_PATH.write_text(text, encoding="utf-8")
        print(
            f"[docker-env] Repaired keys in {ENV_PATH.relative_to(ROOT).as_posix()} "
            "(values not printed; POSTGRES_* untouched):"
        )
        for key in changed:
            print(f"  - {key}")
    else:
        print(
            f"[docker-env] Using existing {ENV_PATH.relative_to(ROOT).as_posix()} "
            "(no secret rotation)."
        )

    print(f"[docker-env] Panel: http://127.0.0.1:{port}/  (user: {username})")
    if not CREDENTIALS_PATH.is_file():
        boot = (_get_env_value(text, "BOOTSTRAP_ADMIN_PASSWORD") or "").strip()
        if boot:
            _write_credentials(username, boot, port)
            print(f"[docker-env] Wrote {CREDENTIALS_PATH.relative_to(ROOT).as_posix()} (no echo of secrets)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
