@echo off
setlocal EnableExtensions
set "ERR=0"

REM Windows 10/11 agent runner.
REM This is the same logic as agent\inventory_send.bat, but kept under win10-11\ for clarity.

cd /d "%~dp0"
title INVENTORY AGENT :: SECURE UPLINK
color 0A

if /i "%~1"=="nopause" set "INV_NOPAUSE=1"

if not defined INV_NOPAUSE if exist "%~dp0inventory_splash.ps1" (
  powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0inventory_splash.ps1"
)

REM Optional local config (generated by tools\setup_agent_env.py)
if exist "%~dp0agent_env.bat" (
  call "%~dp0agent_env.bat"
)

REM Required configuration (do NOT hardcode secrets in this repo).
REM Set these via GPO/Intune/SCCM or locally before running:
REM   set INVENTORY_SERVER=http://192.168.1.10:3001
REM   set AGENT_TOKEN=<token>

REM - If 1st argument looks like http(s)://... use it as INVENTORY_SERVER
echo %~1 | findstr /I /R "^http:// ^https://">NUL
if "%ERRORLEVEL%"=="0" set "INVENTORY_SERVER=%~1"
if not defined INVENTORY_SERVER (
  echo [BAT] ERROR: INVENTORY_SERVER is not set. Example:
  echo [BAT]   set INVENTORY_SERVER=http://192.168.1.10:3001
  set "ERR=2"
  goto :done
)
if not defined AGENT_TOKEN (
  echo [BAT] ERROR: AGENT_TOKEN is not set. Ask admin for an agent token.
  set "ERR=2"
  goto :done
)

REM ---------- Optional: after a successful send, register Task Scheduler ----------
set "SCHEDULE_ENABLE=0"
set "SCHEDULE_MODE=WEEKLY"
set "SCHEDULE_TIME=09:00"
set "SCHEDULE_WEEKDAY=MON"
set "SCHEDULE_DAY_OF_MONTH=1"
set "SCHEDULE_TASK_NAME=InventoryAgent-Scheduled"
REM ------------------------------------------------------------------------------

echo.
echo  // SESSION ------------------------------------------------
echo  // START     %DATE% %TIME%
echo  // CWD       %CD%
echo  // TARGET    %INVENTORY_SERVER%
echo  // NOTE      API port is usually 3001 (start_all.bat / production)
if /i "%SCHEDULE_ENABLE%"=="1" echo  // SCHEDULE  %SCHEDULE_MODE% %SCHEDULE_TIME% after OK
echo  // ---------------------------------------------------------
echo.

if not exist "%~dp0InventoryClient.ps1" (
  echo  [FAIL] InventoryClient.ps1 not found:
  echo         %~dp0
  set "ERR=1"
  goto :done
)

echo  [RUN]  InventoryClient.ps1
echo  [RUN]  WMI + registry ^> JSON ^> POST (timeout 45s)
echo.

set "INV_PS1=%~dp0InventoryClient.ps1"
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%INV_PS1%"
set "ERR=%ERRORLEVEL%"

echo.
echo  // EXIT CODE  %ERR%
echo  // FINISHED   %DATE% %TIME%
if "%ERR%"=="0" (
  echo  // STATUS     UPLINK OK
) else (
  echo  // STATUS     UPLINK FAILED
)
echo.

if "%ERR%"=="0" if /i "%SCHEDULE_ENABLE%"=="1" (
  echo.
  echo  [TASK] Registering %SCHEDULE_TASK_NAME% ...
  powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0register_scheduled_task.ps1" -AgentRoot "%~dp0" -Schedule "%SCHEDULE_MODE%" -StartTime "%SCHEDULE_TIME%" -TaskName "%SCHEDULE_TASK_NAME%" -WeekDay "%SCHEDULE_WEEKDAY%" -DayOfMonth %SCHEDULE_DAY_OF_MONTH%
)

:done
if not "%ERR%"=="0" echo.
if not defined INV_NOPAUSE pause
endlocal & exit /b %ERR%

