#!/usr/bin/env python3
"""
One-command setup for Windows agents:
- Generates a new agent token via backend API (requires running server).
- Writes agent/win10-11/agent_env.bat (and win7 one) with INVENTORY_SERVER + AGENT_TOKEN.
- Optionally persists env vars via `setx` for the current user.

Usage (from repo root):
  python tools/setup_agent_env.py
  python tools/setup_agent_env.py --server http://127.0.0.1:3001
  python tools/setup_agent_env.py --token "paste-any-token"
  python tools/setup_agent_env.py --no-setx
"""

from __future__ import annotations

import argparse
import os
import platform
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

import requests


_ENV_LINE_RE = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$")


def _read_dotenv(path: Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    out: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        m = _ENV_LINE_RE.match(line)
        if not m:
            continue
        k, v = m.group(1), m.group(2)
        # Strip optional quotes
        if len(v) >= 2 and ((v[0] == v[-1] == '"') or (v[0] == v[-1] == "'")):
            v = v[1:-1]
        out[k] = v
    return out


def _upsert_dotenv_line(path: Path, key: str, value: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    if path.is_file():
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    out: list[str] = []
    found = False
    for raw in lines:
        m = _ENV_LINE_RE.match(raw.strip())
        if m and m.group(1) == key:
            out.append(f"{key}={value}")
            found = True
        else:
            out.append(raw)
    if not found:
        if out and out[-1].strip() != "":
            out.append("")
        out.append(f"{key}={value}")
    path.write_text("\n".join(out) + "\n", encoding="utf-8", errors="strict")


def _session_no_proxy() -> requests.Session:
    s = requests.Session()
    # Ignore HTTP(S)_PROXY / system proxy. Local dev servers must not go through proxy.
    s.trust_env = False
    return s


def _healthcheck(sess: requests.Session, server: str) -> bool:
    try:
        r = sess.get(f"{server.rstrip('/')}/api/v1/health", timeout=4)
        return r.status_code < 500
    except requests.RequestException:
        return False


def _http_post_json(
    sess: requests.Session,
    url: str,
    json_body: dict[str, Any],
    headers: dict[str, str] | None = None,
) -> dict[str, Any]:
    r = sess.post(url, json=json_body, headers=headers, timeout=20)
    if r.status_code >= 400:
        raise RuntimeError(f"HTTP {r.status_code}: {r.text}")
    data = r.json()
    if not isinstance(data, dict):
        raise RuntimeError("Unexpected JSON response")
    return data


def _login_get_bearer(sess: requests.Session, server: str, username: str, password: str) -> str:
    url = f"{server.rstrip('/')}/api/v1/auth/login/json"
    data = _http_post_json(sess, url, {"username": username, "password": password, "return_token": True})
    token = (data.get("access_token") or "").strip()
    if not token:
        raise RuntimeError("Login succeeded but access_token is empty")
    return token


def _create_agent_token(
    sess: requests.Session,
    server: str,
    bearer: str,
    label: str | None,
    allowed_hostname: str | None,
) -> str:
    url = f"{server.rstrip('/')}/api/v1/agent-tokens"
    headers = {"Authorization": f"Bearer {bearer}"}
    body: dict[str, Any] = {"label": label, "allowed_hostname": allowed_hostname}
    data = _http_post_json(sess, url, body, headers=headers)
    token = (data.get("token") or "").strip()
    if not token:
        raise RuntimeError("Token creation succeeded but token is empty")
    return token


def _write_agent_env_bat(path: Path, server: str, agent_token: str) -> None:
    # Use delayed expansion-safe form with quotes.
    content = (
        "@echo off\r\n"
        "REM Auto-generated by tools\\setup_agent_env.py\r\n"
        f'set "INVENTORY_SERVER={server}"\r\n'
        f'set "AGENT_TOKEN={agent_token}"\r\n'
        "\r\n"
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", errors="strict", newline="")


def _setx(name: str, value: str) -> None:
    # Persist for current user. Requires a new terminal process to take effect.
    # setx quoting is tricky; pass as single argument to cmd.
    cmd = ["cmd", "/c", "setx", name, value]
    subprocess.run(cmd, check=True, capture_output=True, text=True)


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    p = argparse.ArgumentParser()
    p.add_argument("--server", default=os.environ.get("INVENTORY_SERVER", "http://127.0.0.1:3001"))
    p.add_argument("--token", default="")
    p.add_argument("--no-setx", action="store_true", help="do not persist env vars via setx")
    p.add_argument(
        "--offline",
        action="store_true",
        help="do not call API; generate local AGENT_TOKEN and write backend/.env",
    )
    p.add_argument("--label", default="auto")
    p.add_argument("--allowed-hostname", default="auto")
    p.add_argument("--admin-user", default="")
    p.add_argument("--admin-pass", default="")
    args = p.parse_args()

    server = (args.server or "").strip().rstrip("/")
    if not server:
        print("ERROR: --server is empty", file=sys.stderr)
        return 2

    agent_token = (args.token or "").strip()
    created_via_api = False
    generated_local = False

    if not agent_token:
        sess = _session_no_proxy()
        if args.offline or not _healthcheck(sess, server):
            import secrets

            agent_token = secrets.token_urlsafe(32)
            generated_local = True
        else:
            # Pull bootstrap creds from backend/.env if present.
            env = _read_dotenv(root / "backend" / ".env")
            admin_user = (args.admin_user or env.get("BOOTSTRAP_ADMIN_USERNAME") or "admin").strip()
            admin_pass = (args.admin_pass or env.get("BOOTSTRAP_ADMIN_PASSWORD") or "admin123").strip()

            label = None if args.label == "auto" else (args.label or None)
            allowed_hostname = None
            if args.allowed_hostname == "auto":
                allowed_hostname = platform.node() or None
            else:
                allowed_hostname = args.allowed_hostname or None

            try:
                bearer = _login_get_bearer(sess, server, admin_user, admin_pass)
                agent_token = _create_agent_token(sess, server, bearer, label=label, allowed_hostname=allowed_hostname)
                created_via_api = True
            except requests.RequestException:
                import secrets

                agent_token = secrets.token_urlsafe(32)
                generated_local = True
            except RuntimeError:
                import secrets

                agent_token = secrets.token_urlsafe(32)
                generated_local = True

    # Write agent env files (Win10/11 + Win7 runners).
    win10_env = root / "agent" / "win10-11" / "agent_env.bat"
    win7_env = root / "agent" / "win7" / "agent_env.bat"
    _write_agent_env_bat(win10_env, server, agent_token)
    _write_agent_env_bat(win7_env, server, agent_token)

    if generated_local:
        # Ensure backend picks the same token on next start.
        _upsert_dotenv_line(root / "backend" / ".env", "AGENT_TOKEN", agent_token)
        _upsert_dotenv_line(root / "backend" / ".env", "AGENT_LEGACY_TOKENS", agent_token)

    if os.name == "nt" and not args.no_setx:
        try:
            _setx("INVENTORY_SERVER", server)
            _setx("AGENT_TOKEN", agent_token)
        except Exception as e:
            print(f"WARNING: setx failed: {e}", file=sys.stderr)

    print("OK")
    print(f"INVENTORY_SERVER={server}")
    print(f"AGENT_TOKEN={agent_token}")
    if created_via_api:
        print("(generated via API: /api/v1/agent-tokens)")
    elif generated_local:
        print("(generated locally; also written to backend/.env as AGENT_TOKEN)")
    print()
    print("Next:")
    print(r'  agent\win10-11\inventory_send_win10.bat')
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

