@echo off
setlocal EnableExtensions EnableDelayedExpansion
set "ERR=0"

REM Windows 7 compatible runner (cmd + PowerShell 2.0).
REM Keep this file ASCII-only (no Cyrillic) to avoid cmd encoding issues.

REM Win7 cmd.exe cannot use UNC as current directory. If script is on UNC, map it to a temp drive.
set "INV_SCRIPT_DIR=%~dp0"
set "INV_SELF=%~f0"
set "INV_MAP_DRIVE="
set "INV_UNC_DIR="
echo %INV_SCRIPT_DIR% | findstr /B "\\\\">NUL
if "%ERRORLEVEL%"=="0" set "INV_UNC_DIR=%INV_SCRIPT_DIR%"
if not defined INV_UNC_DIR (
  echo %INV_SELF% | findstr /B "\\\\">NUL
  if "%ERRORLEVEL%"=="0" (
    for %%P in ("%INV_SELF%") do set "INV_UNC_DIR=%%~dpP"
  )
)

if defined INV_UNC_DIR (
  REM Parse \\HOST\SHARE\rest\...
  set "INV_UNC=!INV_UNC_DIR!"
  set "INV_UNC=!INV_UNC:~2!"
  for /f "tokens=1,2,* delims=\\" %%A in ("!INV_UNC!") do (
    set "INV_UNC_HOST=%%A"
    set "INV_UNC_SHARE=%%B"
    set "INV_UNC_REST=%%C"
  )
  if defined INV_UNC_HOST if defined INV_UNC_SHARE (
    for %%D in (Z Y X W V U T S R Q P O N M L K J I H G F E D) do (
      if not exist "%%D:\NUL" (
        net use %%D: "\\!INV_UNC_HOST!\!INV_UNC_SHARE!" /persistent:no >NUL 2>&1
        if "!ERRORLEVEL!"=="0" (
          set "INV_MAP_DRIVE=%%D:"
          goto :mapped_ok
        )
      )
    )
  )
)
:mapped_ok
if defined INV_MAP_DRIVE (
  cd /d "%INV_MAP_DRIVE%\!INV_UNC_REST!" >NUL 2>&1
  if errorlevel 1 cd /d "%INV_MAP_DRIVE%\" >NUL 2>&1
) else (
  pushd "%~dp0"
)

if /i "%~1"=="nopause" set "INV_NOPAUSE=1"

title INVENTORY AGENT :: WIN7 UPLINK
color 0A

if not defined INV_NOPAUSE if exist "%~dp0inventory_splash_win7.ps1" (
  powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0inventory_splash_win7.ps1"
)

set "LOG_FILE=%TEMP%\inventory_agent_win7.log"

REM Optional local config (generated by tools\setup_agent_env.py)
if exist "%~dp0agent_env.bat" (
  call "%~dp0agent_env.bat"
)

REM Convenience for labs / network share deployment:
REM - If 1st arg looks like http(s)://... use it as INVENTORY_SERVER
REM - UNC path (\\fileserver\share\...) is ONLY for reading scripts; API host is NOT inferred from it.
REM - Default: none — set INVENTORY_SERVER in agent_env.bat or pass URL as 1st arg.
set "INV_SERVER_FROM_ARG="
echo %~1 | findstr /I /R "^http:// ^https://">NUL
if "%ERRORLEVEL%"=="0" (
  set "INVENTORY_SERVER=%~1"
  set "INV_SERVER_FROM_ARG=1"
)
REM INV_SELF already set above
set "INV_UNC_HOST="
set "INV_UNC_SHARE="
REM Prefer %~f0 because %~dp0 may be a mapped drive (Z:\...) even when original path is UNC.
echo %INV_SELF% | findstr /B "\\\\">NUL
if "%ERRORLEVEL%"=="0" (
  REM for /f collapses repeated delimiters, so \\HOST\SHARE\... => token1=HOST token2=SHARE
  for /f "tokens=1,2 delims=\\" %%H in ("%INV_SELF%") do (
    set "INV_UNC_HOST=%%H"
    set "INV_UNC_SHARE=%%I"
  )
)
REM Fallback to %~dp0 if %~f0 isn't UNC (some setups may rewrite).
if not defined INV_UNC_HOST (
  echo %~dp0 | findstr /B "\\\\">NUL
  if "%ERRORLEVEL%"=="0" (
    for /f "tokens=1,2 delims=\\" %%H in ("%~dp0") do (
      set "INV_UNC_HOST=%%H"
      set "INV_UNC_SHARE=%%I"
    )
  )
)

REM ---- Configure these two lines ----
REM Required env vars (do NOT hardcode secrets in this repo):
REM   set INVENTORY_SERVER=http://<server>:3001
REM   set AGENT_TOKEN=<token>
set "INV_DEBUG=1"

REM If agent_env.bat was generated for local dev (127.0.0.1/localhost),
REM override it for Win7 lab deployment to the real server.
if /i "%INVENTORY_SERVER%"=="http://127.0.0.1:3001" set "INVENTORY_SERVER="
if /i "%INVENTORY_SERVER%"=="http://localhost:3001" set "INVENTORY_SERVER="
if /i "%INVENTORY_SERVER%"=="http://127.0.0.1:3250" set "INVENTORY_SERVER="
if /i "%INVENTORY_SERVER%"=="http://localhost:3250" set "INVENTORY_SERVER="

REM If INVENTORY_SERVER accidentally points at the UNC file-server host/share, clear it.
REM Skip when URL was passed explicitly as 1st argument (admin override).
if not defined INV_SERVER_FROM_ARG (
  if defined INV_UNC_SHARE (
    echo %INVENTORY_SERVER% | findstr /I /C:"http://%INV_UNC_SHARE%:" /C:"https://%INV_UNC_SHARE%:">NUL
    if "%ERRORLEVEL%"=="0" set "INVENTORY_SERVER="
  )
  if defined INV_UNC_HOST (
    echo %INVENTORY_SERVER% | findstr /I /C:"http://%INV_UNC_HOST%:" /C:"https://%INV_UNC_HOST%:">NUL
    if "%ERRORLEVEL%"=="0" set "INVENTORY_SERVER="
  )
)
if not defined INVENTORY_SERVER (
  echo [BAT] ERROR: INVENTORY_SERVER is not set.
  set "ERR=2"
  goto :done
)
if not defined AGENT_TOKEN (
  echo [BAT] ERROR: AGENT_TOKEN is not set. Ask admin for an agent token.
  set "ERR=2"
  goto :done
)

echo.
echo  // SESSION ------------------------------------------------
echo  // START     %DATE% %TIME%
echo  // CWD       %CD%
if defined INV_UNC_HOST echo  // UNC HOST  %INV_UNC_HOST%
if defined INV_UNC_SHARE echo  // UNC SHARE %INV_UNC_SHARE%
if defined INV_MAP_DRIVE echo  // UNC MAP   %INV_MAP_DRIVE%
echo  // TARGET    %INVENTORY_SERVER%
echo  // LOG       %LOG_FILE%
echo  // ---------------------------------------------------------
echo.

if not exist "%~dp0InventoryClient_win7.ps1" (
  echo  [FAIL] InventoryClient_win7.ps1 not found:
  echo         %~dp0
  set "ERR=1"
  goto :done
)

echo  [RUN]  InventoryClient_win7.ps1
echo  [RUN]  WMI + registry ^> JSON ^> POST
echo.

echo ============================================================>>"%LOG_FILE%"
echo [%DATE% %TIME%] start: %~f0>>"%LOG_FILE%"
echo [%DATE% %TIME%] cwd: %CD%>>"%LOG_FILE%"
echo [%DATE% %TIME%] INVENTORY_SERVER=%INVENTORY_SERVER%>>"%LOG_FILE%"
echo [%DATE% %TIME%] INV_DEBUG=%INV_DEBUG%>>"%LOG_FILE%"
echo ============================================================>>"%LOG_FILE%"

powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0InventoryClient_win7.ps1" 1>>"%LOG_FILE%" 2>>&1
set "ERR=%ERRORLEVEL%"

echo.
echo  // EXIT CODE  %ERR%
echo  // FINISHED   %DATE% %TIME%
if "%ERR%"=="0" (
  echo  // STATUS     UPLINK OK
) else (
  echo  // STATUS     UPLINK FAILED
  echo.
  echo  [FAIL] See log: %LOG_FILE%
)

:done
if not "%ERR%"=="0" echo.
if not defined INV_NOPAUSE pause
if defined INV_MAP_DRIVE (
  net use %INV_MAP_DRIVE% /delete /y >NUL 2>&1
) else (
  popd
)
endlocal & exit /b %ERR%

