namespace Corax.Client;

internal static class ConfigSlot
{
    internal const string Slot =
        "<<<CORAX_CFG_BEGIN>>>" +
        "{}" +
        "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                " +
        "<<<CORAX_CFG_END>>>";
}
